export PARTITIONED_HDB_HOME=${PWD}
export PARTITIONED_HDB_LOG=${PARTITIONED_HDB_HOME}/tpLog
export PARTITIONED_HDB_SCHEMA=${PARTITIONED_HDB_HOME}/schema
export PARTITIONED_HDB_HDBDIR=${PARTITIONED_HDB_HOME}/QHDB
export PARTITIONED_HDB_SCRIPTS=${PARTITIONED_HDB_HOME}/scripts


